[package]
name = "dictionary-builder"
version = "0.1.0"
authors = ["rsookram <rashadsookram@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
rusqlite = {version = "0.23.1", features=["bundled"]}
byteorder = "1.3.4"
