[package]
name = "dictionary-builder"
version = "0.1.0"
authors = ["rsookram <rashadsookram@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.26"
rusqlite = {version = "0.28.0", features=["bundled"]}
byteorder = "1.4.3"
anyhow = "1.0.66"

[profile.release]
lto = true
codegen-units = 1
